# Generated by Django 4.1 on 2022-09-14 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_caver_alter_comment_body_alter_comment_stars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='caver',
            new_name='cover',
        ),
    ]
