# Generated by Django 4.1 on 2022-09-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_caver_product_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-datetime_created']},
        ),
        migrations.AddField(
            model_name='product',
            name='dd',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
